runtime: nodejs18
env: standard
entrypoint: npm start

instance_class: F2

env_variables:
  MONGO_URI: "mongodb+srv://chetanshanbhag24:TmmUYrUcsahX0oOV@cluster0.w9ofs.mongodb.net/vehicleDashboard?retryWrites=true&w=majority"
